# Generated by Django 2.2.5 on 2019-12-03 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_tel', models.CharField(blank=True, max_length=10, null=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_typeName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Level_study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=30)),
                ('remind', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_pin', models.CharField(blank=True, max_length=128, null=True)),
                ('user_tel', models.CharField(blank=True, max_length=10, null=True)),
                ('user_stID', models.CharField(blank=True, max_length=15, null=True)),
                ('user_stYear', models.IntegerField(blank=True, null=True)),
                ('user_Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.Department')),
                ('user_officerPosition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.OfficerPosition')),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user_stFaculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.Faculty')),
                ('user_stLevel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.Level_study')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=10)),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.FormType')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.AllForm')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.State')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.Step')),
            ],
        ),
        migrations.CreateModel(
            name='Deadline_step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLA', models.TimeField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.Step')),
            ],
        ),
        migrations.CreateModel(
            name='Bookplace_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('book_datetime_being', models.CharField(blank=True, max_length=10, null=True)),
                ('book_datetime_end', models.CharField(blank=True, max_length=10, null=True)),
                ('air', models.CharField(blank=True, max_length=3, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.AllForm')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.Place')),
            ],
        ),
        migrations.AddField(
            model_name='allform',
            name='form_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.FormType'),
        ),
        migrations.AddField(
            model_name='allform',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
