# Generated by Django 2.2.5 on 2019-11-09 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Level_study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pin', models.CharField(max_length=128)),
                ('user_tel', models.CharField(max_length=20)),
                ('user_stYear', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_DepartmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.Department')),
                ('user_officerPositionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.OfficerPosition')),
                ('user_stFacultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.Faculty')),
                ('user_stLevelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.Level_study')),
            ],
        ),
    ]
