# Generated by Django 2.2.5 on 2019-11-17 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='action',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='role',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
