# Generated by Django 2.2.5 on 2019-12-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookplace_form',
            name='book_datetime_being',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='bookplace_form',
            name='book_datetime_end',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
