# Generated by Django 2.2.5 on 2019-11-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userID',
            new_name='user_name',
        ),
    ]
