# Generated by Django 2.2.5 on 2019-11-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_auto_20191104_1401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
