# Generated by Django 2.2.5 on 2019-11-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_auto_20191118_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='remind',
            field=models.TextField(blank=True, null=True),
        ),
    ]
